### ISSUE TITLE
python3 / pep 404 : implicit relative imports within packages are no longer available

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/S3DXRD#8]
Hi @AxelHenningsson: I can run the strain_fitter code under python 2 after patching ImageD11.grain to bring back u/ub. Under python3 I need to fiddle with the imports. The goal here was to run the PCR fitting for orientation gradients, so please point me at a different package if I am looking in the wrong place. I will try to send a patch...

**Comment by AxelHenningsson** [comment]
Feel free to have a go. At the time the PCR was implementerad to demonstrate that we could get similar strain fields out even if we included orientations into the inverse s3dxrd problem. Since then there has been little progress, that I am aware of, on fitting orientation gradients in s3dxrd, and I still think the community lacks a robust and fast algorithm for it. My experience from the PCR was that it could get stuck in local minima and be a bit slow which is why we used more of the decoupled strain solvers since then. But if you can make it run and get something useful out of it, that is great! I do not have any other code for fitting orientations as I have worked almost exclusively on elastic strain.

**Comment by jonwright** [comment]
Thanks! I will merge this and let you know if I make any progress.  It seems there might be some more bitrot somewhere - the behavior in python2 was more reliable so far - I saw a few different errors that I am having trouble to reproduce.
